### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by meghprkh** [felicity-buzz-2k16/buzz2k16-main-website#3]
- [x] Redesign map to feature town square with Felicity buzz in cool pix font with a few characters there
- [x] Window in top right corner telling instructions that fades out in 2 seconds OR
  Grey transparent overlay showing instructions fades out in 2 seconds or on key press
- [x] WASD for moving
- [ ] OPTIONAL
  - [x] Add IIIT stuff like Juice bhaiya
  - [ ] Running tom and jerry
